### ISSUE TITLE
表示機能についての質問です

### ISSUE THREAD

**Issue by potkrin** [gobosan/d-comments#14]
素晴らしい拡張機能をありがとうございます！ こちらの拡張機能を試してみたところ、再生画面の右にコメントリストが表示され自動でスクロールされるのを確認しました。再生画面上にオーバーレイのような形で表示する機能はありますか？

**Comment by gobosan** [comment]
現時点でそのような機能はありませんが、実装はそれほど難しくないはずです...！

**Comment by gobosan** [comment]
#19 でコメントリストをオーバーレイ表示する設定を実装しました！

[Version.2022.12.18](https://github.com/gobosan/d-comments/releases/tag/v2022.12.18) から β版 として設定が追加されます！

**Comment by gobosan** [comment]
とりあえず実装したのでこの Issue はクローズしますが、また御不明の点等があれば御遠慮なくどうぞ :octocat:
